### ISSUE TITLE
mkr wrapの-d(--detail)オプションで、先頭の1024文字の出力ではなく末尾から1024文字というオプションを追加して欲しい

### ISSUE THREAD

**Issue by book000** [mackerelio/mkr#199]
場所が異なりましたら申し訳ございません。毎日有効活用させていただいております。  
mkr wrapにおいて、-dオプションで出力の先頭1024文字をMackerelで確認できるようになりますが、この出力の切り出しを末尾1024文字に変更するオプションを追加していただきたく存じます。  
エラーで異常終了した際、大抵のエラーは末尾に出力されます。mkr wrapを導入したことにより「プログラムが異常終了した」ということはわかるものの、肝心のエラー内容がカットされてしまい、手動で実行し直さないと原因を特定できないことが多くありました。  
よろしくお願いいたします。

English(Google Translate):
In mkr wrap, you can use Mackerel to check the first 1024 characters of output with -d option, but I would like you to add an option to change the logging of this output to the last 1024 characters.
When abnormal termination due to errors, most errors are output at the end. Although the introduction of mkr wrap shows that "the program has terminated abnormally", the important error content has been cut, and in many cases the cause can not be identified unless it is re-executed manually.

**Comment by Songmu** [comment]
It is a good suggestion.

I think this is a reasonable requirement, so we would like to think about whether this should be the default behavior or provide a new option (such as the -D option).

Also, you can send pull requests about it.
