### ISSUE TITLE
The mackerel-client-go alias imports seem confusing

### ISSUE THREAD

**Issue by stefafafan** [mackerelio/mkr#261]
I noticed while reading the code that this product uses https://github.com/mackerelio/mackerel-client-go .

That seems to be a good idea but the way it is imported seemed to be confusing to me.

Here is all the occurrences of mackerel-client-go in the *.go files:
```sh
$ git grep "github.com/mackerelio/mackerel-client-go" -- "*.go"
alerts.go:      mkr "github.com/mackerelio/mackerel-client-go"
alerts_test.go: mkr "github.com/mackerelio/mackerel-client-go"
annotations.go: mkr "github.com/mackerelio/mackerel-client-go"
commands.go:    mkr "github.com/mackerelio/mackerel-client-go"
dashboards.go:  mackerel "github.com/mackerelio/mackerel-client-go"
hosts/app.go:   mackerel "github.com/mackerelio/mackerel-client-go"
hosts/app_test.go:      mackerel "github.com/mackerelio/mackerel-client-go"
mackerelclient/client.go:import mackerel "github.com/mackerelio/mackerel-client-go"
mackerelclient/mock_client.go:import mackerel "github.com/mackerelio/mackerel-client-go"
mackerelclient/new.go:  mackerel "github.com/mackerelio/mackerel-client-go"
monitors.go:    mkr "github.com/mackerelio/mackerel-client-go"
monitors_test.go:       mkr "github.com/mackerelio/mackerel-client-go"
org/app_test.go:        mackerel "github.com/mackerelio/mackerel-client-go"
services/app_test.go:   mackerel "github.com/mackerelio/mackerel-client-go"
throw.go:       mkr "github.com/mackerelio/mackerel-client-go"
throw_test.go:  mkr "github.com/mackerelio/mackerel-client-go"
wrap/wrap.go:   mackerel "github.com/mackerelio/mackerel-client-go"
wrap/wrap_test.go:      mackerel "github.com/mackerelio/mackerel-client-go"
```

### The `mackerel` alias import

https://github.com/mackerelio/mkr/blob/2d2b7974454b8fdadef4341eca919655237d56e6/dashboards.go#L10

For this case, I guess you can make it clear that the methods starting by `mackerel` come from mackerel-client-go (like below):

https://github.com/mackerelio/mkr/blob/2d2b7974454b8fdadef4341eca919655237d56e6/dashboards.go#L431-L435

However when I check mackerel-client-go, its package seems to be `mackerel` so if I am correct, this alias import might have no meaning?

https://github.com/mackerelio/mackerel-client-go/blob/2ef887b55f6ab39f8ba8853904c3cdef82ad0281/dashboards.go#L1

### The `mkr` alias import

This is the other variation being used in the code. 

https://github.com/mackerelio/mkr/blob/2d2b7974454b8fdadef4341eca919655237d56e6/alerts.go#L13

I guess it makes sense when you don't want to write `mackerel` over and over again in the code. `mkr` is shorter.

https://github.com/mackerelio/mkr/blob/2d2b7974454b8fdadef4341eca919655237d56e6/alerts.go#L77-L79

But the name of this repository is `mkr` as well, and having `mkr` import `mackerel-client-go` as `mkr` seemed very confusing to me at first.

### Suggestion

To make these imports more clear I suggest maybe one of the following.

- Since mackerel-client-go's package name is already `mackerel` , perhaps stop using alias imports and just use `mackerel.*` when calling functions
- Maybe rename the package of mackerel-client-go? ( like, mackerelclient ? )
- I noticed `mkr/mackerelclient/client.go` , maybe add methods here and try to only use this?

https://github.com/mackerelio/mkr/blob/2d2b7974454b8fdadef4341eca919655237d56e6/mackerelclient/client.go#L1

---

I see that other products like mackerel-agent also import like this sometimes, but I guess it just seemed the most confusing for me when `mkr` is used in the `mkr` repository.
https://github.com/mackerelio/mackerel-agent/blob/09845f03232f6425647b80ef8b6603fd75b829e4/metrics/metrics.go#L3

**Comment by lufia** [comment]
I think these import names can be unified to `mackerel`. `mkr` is the command name, so I recommend to use `mackerel`. As you say, the aliases could just be removed.

(IMHO) Though the mackerel-agent repository has `mackerel` package internally, thus  `mkr` alias was needed, the mkr repository don't have naming conflict. Probably it might be a liking of a code author.

**Comment by stefafafan** [comment]
@lufia Thank you for the comment!

I figured I could just make a pull request for this myself, so I've done it here: #263
