### ISSUE TITLE
suggestion: show usage of mandatory flags in modern CLI manner

### ISSUE THREAD

**Issue by aereal** [mackerelio/mkr#272]
mkr shows all of flags with brackets; such as:

```
USAGE:
   mkr annotations list [command options] [--from <from>] [--to <to>] [--service -s <service>]
```

But all of above flags are mandatory and I confused.

Modern CLIs, such as gcloud or aws cli, show usage of mandatory flags with no brackets and optional flags with brackets, to my understanding.

```
gcloud iam service-accounts keys list --iam-account=IAM_ACCOUNT [--created-before=CREATED_BEFORE] [--managed-by=MANAGED_BY; default="any"] [--filter=EXPRESSION] [--limit=LIMIT] [--page-size=PAGE_SIZE] [--sort-by=[FIELD,…]] [--uri] [GCLOUD_WIDE_FLAG …]
```

https://cloud.google.com/sdk/gcloud/reference/iam/service-accounts/keys/list

It maybe not defined as standard but change mkr to conform to the manner looks good.

If this suggestion is approved, I have an intention to fix them.

**Comment by astj** [comment]
@aereal Hi, thank you for feedback and suggestion.
Your suggestion looks good. We will welcome for your patches.
