### ISSUE TITLE
In case of monitoring rule by expression exists, fail to `diff`, `push` subcommand.

### ISSUE THREAD

**Issue by a-know** [mackerelio/mkr#65]
```
$ mkr -v
mkr version 0.11.2
$ mkr monitors diff                               
     error Unknown type is found: expression
```

Probably, a cause is that [`validateRules` function in monitors.go](https://github.com/mackerelio/mkr/blob/de4a276cbacb0693444374ae202058484a312e51/monitors.go#L292) not considering `expression` type.

(I created a monitoring rule by expression with using Mackerel Web UI.)

**Comment by daiksy** [comment]
thank you!!
#66 fix this!

**Comment by a-know** [comment]
Thank you, too!! 😆
